### ISSUE TITLE
[SUGESTÃO] - listar os comandos de forma detalhada

### ISSUE THREAD

**Issue by luan0ap** [darkcode357/thg-framework#5]
Ao listar os comandos com o `help` me deparei com uma série de palavras que para quem não tem muito entendimento, não fazem sentido. Se o THG tem como objetivo bater de frente com o Metasploit sugiro, fazer um `help` dos comandos e explicar resumidamente eles, como o Metasploit faz.

**Comment by darkcode357** [comment]
Ok, muito obrigado. irei aplicar ao projeto

**Comment by darkcode357** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mudar ORM de SQLI para SQLAlchemy](https://trello.com/c/quRYuVbp/3-mudar-orm-de-sqli-para-sqlalchemy)

**Comment by luan0ap** [comment]
Bot automático isso?

**Comment by darkcode357** [comment]
acho que sim kkkkk
