### ISSUE TITLE
Substituir a biblioteca responsável pela iteração com o banco de dados e a linguagem python, de SQLI para NoSQL  **[mangodb](https://docs.mongodb.com/)** 

### ISSUE THREAD

**Issue by darkcode357** [darkcode357/thg-framework#7]
dsadadadad

**Comment by darkcode357** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mudar ORM de SQLI para SQLAlchemy](https://trello.com/c/quRYuVbp/3-mudar-orm-de-sqli-para-sqlalchemy)

**Comment by darkcode357** [comment]
clouse

**Comment by KillerBean** [comment]
DB Changed to  MongoDB
